//change this to your own servlet mapped url
var servletUrl = "Reports"

function overrideNames()
{
	//Any fields for which you want to change the display name go here
	//ex. setName(UNIQUE_IDENTIFIER, "blah");
	//setName(UNIT, "Unit/Suite/Apt #: ");
}

function generatePageElements()
{
	//////////////////////////////////////////////////////////////////////////////////////////////////////////
	//////////////////////////////		  NEW FIELDS GO HERE                                         /////////
	//////////////////////////////////////////////////////////////////////////////////////////////////////////
	addFieldElement(DATE_OF_BIRTH_YYYY_MM_DD);
	addFieldElement(POSTAL_CODE_WHERE_THE_SERVICE_WAS_RECEIVED);
	addFieldElement(START_DATE_OF_ASSESSMENT_YYYY_MM_DD);
	addFieldElement(LANGUAGE_OF_SERVICE);
	addFieldElement(OFFICIAL_LANGUAGE_OF_PREFERENCE);
	addFieldElement(TYPE_OF_INSTITUTION_ORGANIZATION_WHERE_CLIENT_RECEIVED_SERVICES);
	addFieldElement(REFERRED_BY);
	addFieldElement(INCREASE_KNOWLEDGE_OF_LIFE_IN_CANADA);
	addFieldElement(INCREASE_KNOWLEDGE_OF_LIFE_IN_CANADA_REFERRALS);
	addFieldElement(INCREASE_KNOWLEDGE_OF_COMMUNITY_AND_GOVERNMENT_SERVICES);
	addFieldElement(INCREASE_KNOWLEDGE_OF_COMMUNITY_AND_GOVERNMENT_SERVICES_REFERRALS);
	addFieldElement(INCREASE_KNOWLEDGE_OF_WORKING_IN_CANADA);
	addFieldElement(INCREASE_KNOWLEDGE_OF_WORKING_IN_CANADA_REFERRALS);
	addFieldElement(INCREASE_KNOWLEDGE_OF_EDUCATION_IN_CANADA);
	addFieldElement(INCREASE_KNOWLEDGE_OF_EDUCATION_IN_CANADA_REFERRALS);
	addFieldElement(INCREASE_THE_FOLLOWING_SOCIAL_NETWORKS);
	addFieldElement(INCREASE_THE_FOLLOWING_SOCIAL_NETWORKS_REFERRALS);
	addFieldElement(INCREASE_THE_FOLLOWING_PROFESSIONAL_NETWORKS);
	addFieldElement(INCREASE_THE_FOLLOWING_PROFESSIONAL_NETWORKS_REFERRALS);
	addFieldElement(INCREASE_THE_FOLLOWING_ACCESS_TO_LOCAL_COMMUNITY_SERVICES);
	addFieldElement(INCREASE_THE_FOLLOWING_ACCESS_TO_LOCAL_COMMUNITY_SERVICES_REFERRALS);
	addFieldElement(INCREASE_THE_FOLLOWING_LEVEL_OF_COMMUNITY_INVOLVEMENT);
	addFieldElement(INCREASE_THE_FOLLOWING_LEVEL_OF_COMMUNITY_INVOLVEMENT_REFERRALS);
	addFieldElement(IMPROVE_LANGUAGE_SKILLS);
	addFieldElement(IMPROVE_LANGUAGE_SKILLS_REFERRALS);
	addFieldElement(IMPROVE_LANGUAGE_SKILLS_TO);
	addFieldElement(IMPROVE_OTHER_SKILLS);
	addFieldElement(IMPROVE_OTHER_SKILLS_REFERRALS);
	addFieldElement(IMPROVE_OTHER_SKILLS_TO);
	addFieldElement(FIND_EMPLOYMENT);
	addFieldElement(FIND_EMPLOYMENT_REFERRALS);
	addFieldElement(FIND_EMPLOYMENT_TIMEFRAME);
	addFieldElement(FIND_EMPLOYMENT_MINIMUM_ONE_YEARS_WORK_EXPERIENCE);
	addFieldElement(FIND_EMPLOYMENT_INTENDS_TO_WORK_IN_AN_OCCUPATION_CORRESPONDING_TO_WHICH_NATIONAL_OCCUPATION_CLASSIFICATION_SKILL_LEVEL);
	addFieldElement(FIND_EMPLOYMENT_INTENDS_TO_OBTAIN_CREDENTIAL_RECOGNITION_OR_OBTAIN_LICENSE_TO_WORK_IN_CANADA);
	addFieldElement(CLIENT_INTENDS_TO_BECOME_A_CANADIAN_CITIZEN);
	addFieldElement(SUPPORT_SERVICES_MAY_BE_REQUIRED);
	addFieldElement(CARE_FOR_NEWCOMER_CHILDREN_ADULT);
	addFieldElement(TRANSPORTATION_ADULT);
	addFieldElement(PROVISIONS_FOR_DISABILITIES_ADULT);
	addFieldElement(TRANSLATION_ADULT);
	addFieldElement(INTERPRETATION_ADULT);
	addFieldElement(CRISIS_COUNSELLING_ADULT);
	addFieldElement(NON_IRCC_PROGRAM_SERVICES_NEEDED);
	addFieldElement(FOOD_CLOTHING_OTHER_MATERIAL_NEEDS);
	addFieldElement(FOOD_CLOTHING_OTHER_MATERIAL_NEEDS_REFERRALS);
	addFieldElement(HOUSING_ACCOMMODATION);
	addFieldElement(HOUSING_ACCOMMODATION_REFERRALS);
	addFieldElement(HEALTH_MENTAL_HEALTH_WELL_BEING);
	addFieldElement(HEALTH_MENTAL_HEALTH_WELL_BEING_REFERRALS);
	addFieldElement(FINANCIAL);
	addFieldElement(FINANCIAL_REFERRALS);
	addFieldElement(FAMILY_SUPPORT);
	addFieldElement(FAMILY_SUPPORT_REFERRALS);
	addFieldElement(LANGUAGE_NON_IRCC);
	addFieldElement(LANGUAGE_NON_IRCC_REFERRALS);
	addFieldElement(EDUCATION_SKILLS_DEVELOPMENT);
	addFieldElement(EDUCATION_SKILLS_DEVELOPMENT_REFERRALS);
	addFieldElement(EMPLOYMENT_RELATED);
	addFieldElement(EMPLOYMENT_RELATED_REFERRALS);
	addFieldElement(LEGAL_INFORMATION_AND_SERVICES);
	addFieldElement(LEGAL_INFORMATION_AND_SERVICES_REFERRALS);
	addFieldElement(COMMUNITY_SERVICES);
	addFieldElement(COMMUNITY_SERVICES_REFERRALS);
	addFieldElement(SUPPORT_SERVICES_RECEIVED);
	addFieldElement(CARE_FOR_NEWCOMER_CHILDREN_CHILD);
	addFieldElement(CHILD_1_AGE);
	addFieldElement(CHILD_1_TYPE_OF_CARE);
	addFieldElement(CHILD_2_AGE);
	addFieldElement(CHILD_2_TYPE_OF_CARE);
	addFieldElement(CHILD_3_AGE);
	addFieldElement(CHILD_3_TYPE_OF_CARE);
	addFieldElement(CHILD_4_AGE);
	addFieldElement(CHILD_4_TYPE_OF_CARE);
	addFieldElement(CHILD_5_AGE);
	addFieldElement(CHILD_5_TYPE_OF_CARE);
	addFieldElement(TRANSPORTATION_CHILD);
	addFieldElement(PROVISIONS_FOR_DISABILITIES_CHILD);
	addFieldElement(TRANSLATION_CHILD);
	addFieldElement(BETWEEN_TRANSLATION);
	addFieldElement(AND_TRANSLATION);
	addFieldElement(INTERPRETATION_CHILD);
	addFieldElement(BETWEEN_INTERPRETATION);
	addFieldElement(AND_INTERPRETATION);
	addFieldElement(CRISIS_COUNSELLING_CHILD);
	addFieldElement(SETTLEMENT_PLAN_COMPLETED_AND_SHARED_WITH_CLIENT);
	addFieldElement(END_DATE_OF_ASSESSMENT_YYYY_MM_DD);
	addFieldElement(REASON_FOR_UPDATE);
}
