//////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////		  NEW LISTS GO HERE                                          /////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////
var LIST_UNIQUE_IDENTIFIER = ["FOSS/GCMS Client ID","Temporary Resident or Minister’s Permit Number","IMM5292, IMM5509, IMM1000 Number"];
var LIST_STREET_TYPE = ["Abbey","Acres","Allée","Alley","Autoroute","Avenue","Bay","Beach","Bend","Boulevard","Bypass","Byway","Campus","Cape","Carré","Carrefour","Centre","Cercle","Chase","Chemin","Circle","Circuit","Close","Common","Concession","Corners","Côte","Cour","Cours","Court","Cove","Crescent ","Croissant","Crossing","CulDeSac","Dale","Dell","Diversion","Downs","Drive","ésplanade","Estate","Expressway","Extension","Farm","Field","Forest","Freeway","Front","Gardens","Gate","Glade","Glen","Green","Grounds","Grove","Harbour","Heath","Heights","Highlands","Highway","Hill","Holl","Île","Impasse","Inlet","Iceland","Key","Knoll","Landing","Lane","Limits","Line","Link","Lookout","Loop","Mall","Manor","Maze","Meadow","Mews","Montée","Moor","Mount","Mountain","Orchard","Parade","Parc","Park","Parkway","Passage","Path","Pathway","Pines","Place","Platau","Plaza","Point","Pointe","Port","Private","Promenade","Quai","Quay","Ramp","Rang","Range","Ridge","Rise","Road","RondPoint","Route","Row","Rue","Ruelle","Run","Sentier","Square","Street","Subdivision","Terrace","Terrasse","Thicket","Towers","Townline","Trail","Turnabout","Vale","Via","View","Village","Villas","Vista","Voie","Work","Way","Wharf","Wood","Wynd","Not Applicable"];
var LIST_STREET_DIRECTION = ["E - East","N - North","NE - Northeast","NW - Northwest","S - South","SE - Southeast","SW - Southwest","W - West"];
var LIST_PROVINCE = ["Newfoundland and Labrador","Prince Edward Island","Nova Scotia","New Brunswick","Québec","Ontario","Manitoba","Saskatchewan","Alberta","Northwest Territories","British Columbia","Yukon","Nunavut"];
var LIST_OFFICIAL_LANGUAGE_OF_PREFERENCE = ["English","French","Unknown/No preference"];

var LIST_IMPROVE_LANGUAGE_SKILLS_TO = ["Find employment", "Get an education", "Participate in Canadian society", "Acquire citizenship"];
var LIST_IMPROVE_OTHER_SKILLS_TO = ["", "Find employment", "Get an education", "Participate in Canadian society", "Acquire citizenship"];
var LIST_FIND_EMPLOYMENT_TIMEFRAME = ["Within one year", "After one year"];
var LIST_FIND_EMPLOYMENT_MINIMUM_ONE_YEARS_WORK_EXPERIENCE = ["", "No", "Yes", " within Canada", "Yes", " outside Canada", "Yes", " both within and outside Canada"];
var LIST_FIND_EMPLOYMENT_INTENDS_TO_WORK_IN_AN_OCCUPATION_CORRESPONDING_TO_WHICH_NATIONAL_OCCUPATION_CLASSIFICATION_SKILL_LEVEL = ["", "O - Management occupations", "A - Professional", "B - Skilled and technical", "C - Intermediate and clerical", "D - Elemental and labourers", "Unknown/not sure"];
var LIST_FIND_EMPLOYMENT_INTENDS_TO_OBTAIN_CREDENTIAL_RECOGNITION_OR_OBTAIN_LICENSE_TO_WORK_IN_CANADA = ["", "Yes", "No", "Unknown/Not sure"];
var LIST_CLIENT_INTENDS_TO_BECOME_A_CANADIAN_CITIZEN = ["", "Yes", "No", "Unknown/Not sure"];
var LIST_A_REFERRAL_TO = ["Another IRCC-funded service", "Other"];
var LIST_EMPLOYMENT_STATUS = ["Unemployed", "Employed part time - less than 30 hours at main or only job", "Employed full time - 30 hours or more at main or only job"];
var LIST_EDUCATION_STATUS = ["Full-time student", "Part-time student", "Full-time training (e.g. language training or job-specific training)", "Part-time training (e.g. language training or job-specific training)", "Not a student"];
var LIST_OCCUPATION_IN_CANADA = ["00 Senior management occupations", "01-05 Specialized middle management occupations", "06 Middle management occupations in retail and wholesale trade and customer serv", "07-09 Middle management occupations in trades", " transportation", " production and ut", "11 Professional occupations in business and finance", "12 Administrative and financial supervisors and administrative occupations", "13 Finance", " insurance and related business administrative occupations", "14 Office support occupations", "15 Distribution", " tracking and scheduling co-ordination occupations", "21 Professional occupations in natural and applied sciences", "22 Technical occupations related to natural and applied sciences", "30 Professional occupations in nursing", "31 Professional occupations in health (except nursing)", "32 Technical occupations in health", "34 Assisting occupations in support of health services", "40 Professional occupations in education services", "41 Professional occupations in law and social", " community and government services", "42 Paraprofessional occupations in legal", " social", " community and education servic", "43 Occupations in front-line public protection services", "44 Care providers and educational", " legal and public protection support occupatio", "51 Professional occupations in art and culture", "52 Technical occupations in art", " culture", " recreation and sport", "62 Retail sales supervisors and specialized sales occupations", "63 Service supervisors and specialized service occupations", "64 Sales representatives and salespersons - wholesale and retail trade", "65 Service representatives and other customer and personal services occupations", "66 Sales support occupations", "67 Service support and other service occupations", " n.e.c.", "72 Industrial", " electrical and construction trades", "73 Maintenance and equipment operation trades", "74 Other installers", " repairers and servicers and material handlers", "75 Transport and heavy equipment operation and related maintenance occupations", "76 Trades helpers", " construction labourers and related occupations", "82 Supervisors and technical occupations in natural resources", " agricultural and ", "84 Workers in natural resources", " agriculture and related production", "86 Harvesting", " landscaping and natural resources labourers", "92 Processing", " manufacturing and utilities supervisors and central control opera", "94 Processing and manufacturing machine operators and related production workers", "95 Assemblers in manufacturing", "96 Labourers in processing", " manufacturing and utilities"];
var LIST_INTENDED_OCCUPATION = ["00 Senior management occupations", "01-05 Specialized middle management occupations", "06 Middle management occupations in retail and wholesale trade and customer serv", "07-09 Middle management occupations in trades", " transportation", " production and ut", "11 Professional occupations in business and finance", "12 Administrative and financial supervisors and administrative occupations", "13 Finance", " insurance and related business administrative occupations", "14 Office support occupations", "15 Distribution", " tracking and scheduling co-ordination occupations", "21 Professional occupations in natural and applied sciences", "22 Technical occupations related to natural and applied sciences", "30 Professional occupations in nursing", "31 Professional occupations in health (except nursing)", "32 Technical occupations in health", "34 Assisting occupations in support of health services", "40 Professional occupations in education services", "41 Professional occupations in law and social", " community and government services", "42 Paraprofessional occupations in legal", " social", " community and education servic", "43 Occupations in front-line public protection services", "44 Care providers and educational", " legal and public protection support occupatio", "51 Professional occupations in art and culture", "52 Technical occupations in art", " culture", " recreation and sport", "62 Retail sales supervisors and specialized sales occupations", "63 Service supervisors and specialized service occupations", "64 Sales representatives and salespersons - wholesale and retail trade", "65 Service representatives and other customer and personal services occupations", "66 Sales support occupations", "67 Service support and other service occupations", " n.e.c.", "72 Industrial", " electrical and construction trades", "73 Maintenance and equipment operation trades", "74 Other installers", " repairers and servicers and material handlers", "75 Transport and heavy equipment operation and related maintenance occupations", "76 Trades helpers", " construction labourers and related occupations", "82 Supervisors and technical occupations in natural resources", " agricultural and ", "84 Workers in natural resources", " agriculture and related production", "86 Harvesting", " landscaping and natural resources labourers", "92 Processing", " manufacturing and utilities supervisors and central control opera", "94 Processing and manufacturing machine operators and related production workers", "95 Assemblers in manufacturing", "96 Labourers in processing", " manufacturing and utilities"];
var LIST_INTERVENTION_TYPE = ["Long Term", "Short Term"];
var LIST_LONG_TERM_INTERVENTION_INTERVENTION_RECEIVED = ["Work placement", "Mentoring", "Preparation for licensure/certification"];
var LIST_LONG_TERM_INTERVENTION_STATUS_OF_INTERVENTION = ["Intervention ended early (i.e. client ended participation)", "Ongoing", "Completed"];
var LIST_LONG_TERM_INTERVENTION_REASON_FOR_LEAVING_INTERVENTION = ["Found Employment", "To attend school", "Medical reason", "Personal reason", "Parental leave / caring for family members", "Lack of support services", "To receive another settlement service", "Obtained citizenship", "Client felt intervention was not meeting current employment needs", "Moved / unable to contact client", "Reason unknown", "Intervention ended by mentor", "Intervention ended by employer", "Intervention ended by third party/volunteer"];
var LIST_LONG_TERM_INTERVENTION_SIZE_OF_EMPLOYER = ["Small-medium enterprise - fewer than 500 employees", "Large enterprise - 500 employees or more"];
var LIST_LONG_TERM_INTERVENTION_PLACEMENT_WAS = ["Paid", "Unpaid"];
var LIST_LONG_TERM_INTERVENTION_HOURS_PER_WEEK = ["Part-time - less than 30 hours at main or only job", "Full-time - 30 hours or more at main or only job"];
var LIST_LONG_TERM_INTERVENTION_CLIENT_MET_MENTOR_REGULARLY_AT = ["Mentor's place of work during work hours", "Other (e.g. coffee shop", " restaurant", " Skype)"];
var LIST_LONG_TERM_INTERVENTION_AVERAGE_HOURS_WEEK_IN_CONTACT_WITH_MENTOR = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10+"];
var LIST_LONG_TERM_INTERVENTION_PROFESSION_TRADE_FOR_WHICH_SERVICES_WERE_RECEIVED = ["Acupuncturists", "Agricultural Equipment Technician", "Agrologists (Agriculture)", "Appliance Service Technician", "Architects", "Audiologists & Speech Pathologists", "Automotive Painter", "Automotive Service Technician", "Baker", "Boilermaker", "Bricklayer", "Cabinetmaker", "Carpenter", "Certified General Accountants", "Certified Management Accountants", "Chartered Accountants", "Chemical Engineer", "Chiropractors", "Civil Engineer", "Civil Technologists & Technicians", "Community Urban Planner", "Concrete Finisher", "Construction Craft Worker", "Construction Electrician", "Cook", "Dental Assistants", "Dental Hygienists", "Dental Technicians or Technologists", "Dentist/Dental Specialist", "Dentists", "Denturists", "Dieticians/Nutritionists", "Drywall Finisher and Plasterer", "Electric Motor System Technician", "Electrical & Electronics Engineer", "Electrical & Electronics Technologists & Technicians", "Elementary School & Kindergarten Teachers", "Embalmers/Funeral Directors", "Floorcovering Installer", "Foresters", "Gas Fitter – Class A", "Gas Fitter – Class B", "Geologists/Geoscientists", "Glazier", "Hairstylist", "Hearing Aid Practitioners", "Heavy Duty Equipment Technician", "Heavy Equipment Operator", "Home Economists", "Hunting Guides", "Industrial & Manufacturing Technologists & Technician", "Industrial Electrician", "Industrial Mechanic (Millwright)", "Instrumentation and Control Technician", "Insulator (Heat and Frost)", "Ironworker (Generalist)", "Ironworker (Reinforcing)", "Ironworker (Structural/Ornamental)", "Land Surveyors", "Landscape Architects", "Landscape Horticulturist", "Lather (Interior Systems Mechanic)", "Lawyers", "Licensed Practical Nurses", "Machinist", "Massage Therapist", "Mechanical Engineer", "Mechanical Technologists & Technicians", "Medical Laboratory Technologists", "Medical Radiation Technicians", "Metal Fabricator (Fitter)", "Midwives", "Mobile Crane Operator", "Mobile Crane Operator (Hydraulic)", "Motor Vehicle Body Repairer (Metal and Paint)", "Motorcycle Mechanic", "Naturopathic Physicians", "Occupational Therapists", "Oil Heat System Technician", "Opticians", "Optometrists", "Painter and Decorator", "Paramedics", "Partsperson", "Pharmacists", "Physicians", "Physiotherapists", "Plumber", "Podiatrists/Chiropodists", "Powerline Technician", "Psychiatric Nurses", "Psychologists", "Real Estate Agents", "Recreation Vehicle Service Technician", "Refrigeration and Air Conditioning Mechanic", "Registered Nurses", "Respiratory Therapists", "Rig Technician", "Roofer", "Secondary School Teachers", "Sheet Metal Worker", "Social Workers", "Sprinkler System Installer", "Steamfitter/Pipefitter", "Tilesetter", "Tool and Die Maker", "Tower Crane Operator", "Translators", "Transport Trailer Technician", "Truck and Transport Mechanic", "Veterinarians", "Welder"];
var LIST_SHORT_TERM_INTERVENTION_SERVICE_RECEIVED = ["Networking opportunities", "Resume screening for referrals service", "Resume added to a matching system", "Employment counselling"];
var LIST_TIME_SPENT_WITH_CLIENT_ADDRESSING_CLIENTS_EMPLOYMENT_NEEDS_MINUTES = ["0", "5", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55"];
var LIST_FORMAT_OF_TRAINING_PROVIDED = ["Blended classroom and online training", "Classroom", "Itinerant teachers", "One-on-one tutoring", "Other distance learning (e.g. videoconferencing)", "Online computer training", "Workplace"];
var LIST_CLASSES_HELD_AT = ["Community organization", "School", "Post secondary institution", "Private sector provider", "Other public institution", "



var listMap = new Object();

function mapListToField(field, list)
{
	listMap[field] = list;
}

function getFieldList(field)
{
	return listMap[field];
}